language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
#  - hhvm

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer --version
  - travis_retry composer global require fxp/composer-asset-plugin --no-plugins
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction --no-progress
# codeception
  - travis_retry composer global require "codeception/codeception=2.1.*" "codeception/specify=*" "codeception/verify=*"
# setup application:
  - |
    cd tests
    codecept build
    cd ..

before_script:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - mysql --version

  # initialize databases
  - mysql -e 'CREATE DATABASE mdm_admin_test;';
  
script:
  - |
    cd tests/web
    php -S localhost:8080 > /dev/null 2>&1 &
    cd ..
    codecept run
